"""Add library_items table

Revision ID: ad98773dfea7
Revises: 13399170aa3a
Create Date: 2025-11-02 15:35:42.181845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad98773dfea7'
down_revision = '13399170aa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_library_user_movie')
    )
    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_items_user_id'))

    op.drop_table('library_items')
    # ### end Alembic commands ###
